# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - where npm
  - node --version
  - npm --version
  - cmd: psexec.exe -l \\marklap"C:\Program Files (x86)\nodejs\npm.cmd" test

build: off

# build version format
version: "{build}"
